# Use an official Alpine Linux as a base image
FROM alpine:latest

# Install necessary packages
RUN apk --no-cache add bash fortune cowsay

# Copy the script into the container
COPY wisecow.sh /usr/local/bin/wisecow.sh

# Make the script executable
RUN chmod +x /usr/local/bin/wisecow.sh

# Set the default command
CMD ["wisecow.sh"]
